# Generated by Django 5.1.1 on 2024-10-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
