# Generated by Django 5.1.1 on 2024-10-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_options_alter_employee_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AddField(
            model_name='employee',
            name='roll',
            field=models.PositiveIntegerField(default=123),
            preserve_default=False,
        ),
    ]
